### ISSUE TITLE
ability to change colors

### ISSUE THREAD

**Issue by aksbhatia** [prelert/kibana-swimlane-vis#1]
Firstly, thanks for the plugin!
Much needed.

I know you called it out in the documentation: "It is not yet possible to alter the number of color bands, nor the colors used for each range."
However, just want to stress that this is a much needed ability for such a plugin.

**Comment by Mick66** [comment]
+1

**Comment by peteharverson** [comment]
Functionality to change the colors for each band is being addressed in #21

**Comment by peteharverson** [comment]
The colors for each band can now be configured using the color pickers added to the Options tab in #21. This functionality was available in the v5.4 releases.

Closing this issue. Note it is not yet possible to add, or remove, color bands. This has been raised as an enhancement request in #6
