### ISSUE TITLE
Make the length of bar portion to the value field

### ISSUE THREAD

**Issue by tianchao-haohan** [prelert/kibana-swimlane-vis#10]
Seems like the attached picture:
![screenshot1](https://cloud.githubusercontent.com/assets/8639363/20202944/6727603c-a7fe-11e6-93d5-7ae47ff2c425.png)

bigger value with longer bar

**Comment by sophiec20** [comment]
The swimlane visualization requires time across the x-axis. The length of the bar represents a length of time i.e. a bucket. Each bucket is the same time interval, which is calculated based on time-aggregations. Whilst it's a neat idea, this request does not really fit with the intended use of this particular swimlane.
