### ISSUE TITLE
Kibana 5.0.2 is out and compatibility is once again broken

### ISSUE THREAD

**Issue by pemontto** [prelert/kibana-swimlane-vis#12]
Kibana 5.0.2 has been released and as such this plugin will need to be updated to be able to work. See also #9

As mentioned before this may become painful, as prelert is now an Elastic company is this something that will be getting fed back internally or should we be raising this issue somewhere else?

**Comment by sophiec20** [comment]
Your feedback has been shared internally. In addition, this issue explains some more of the background and the different points of view. https://github.com/elastic/kibana/issues/9019

**Comment by peteharverson** [comment]
Published a new release for Kibana 5.0.2, which can be found at https://github.com/prelert/kibana-swimlane-vis/releases.

**Comment by pemontto** [comment]
Thanks @sophiec20 and @peteharverson! Will follow developments in that Kibana ticket, my poor search skills only led me to closed tickets related to plugin versions.
