### ISSUE TITLE
Kibana 5.1.2 Support

### ISSUE THREAD

**Issue by SMAPPER** [prelert/kibana-swimlane-vis#13]
Do you know when you will have support for 5.1.2? This is one of my favorite Kibana plugins so thank you for everything.

**Comment by SMAPPER** [comment]
Nevermind. I got this working by changing the version number on package.json. Again, great work on this.

**Comment by nnordrum** [comment]
I would reopen this so there is an actual 5.1.2 release so people can just do

```kibana-plugin install prelert_swimlane_vis```
