### ISSUE TITLE
Build for Kibana 5.1.2

### ISSUE THREAD

**Issue by abierbaum** [prelert/kibana-swimlane-vis#14]
Would love to see a build for the latest Kibana version so we can install directly.

**Comment by sophiec20** [comment]
Elastic 5.2 now provides a heatmap chart which has the option to be used as a date-based swimlane.  It's a very neat visualisation, which will be supported by the Kibana team going forwards. https://www.elastic.co/guide/en/kibana/5.2/index.html

Do you have plans to migrate to 5.2 soon?

**Comment by romaindequidt** [comment]
This PR should help you:
[Upgrade Prelert Kibana swimlane visualization plugin to version 5.1.2](https://github.com/prelert/kibana-swimlane-vis/pull/16)

**Comment by roadrunner** [comment]
Elastic heatmap is so different than swimline. 👍 for PR

**Comment by aruiztinoco** [comment]
I started to use it in Kibana 5.2.2 Just changed version in package.json

**Comment by pemontto** [comment]
I've used the heatmap viz but would still like to keep using the swimlanes, especially for existing dashboards.

**Comment by pemontto** [comment]
The heatmap is still no replacement for the swimlane viz. I'm constantly seeing "There are too many series defined." every time I change the timespan.

**Comment by peteharverson** [comment]
Published releases for Kibana 5.1.1, 5.1.2 and 5.2.2 so closing issue.

Will shortly be publishing releases for 5.3.0 and 5.3.1.
