### ISSUE TITLE
How do you install on 5.3.0?

### ISSUE THREAD

**Issue by RedCloudDC** [prelert/kibana-swimlane-vis#18]
I have tried the following:

1. Fork and change package.json to my version 5.3.0 using install url syntax - error...
Error: Could not find the End of Central Directory Record
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

2. Download zip and use bin/kibana-plugin install file:kibana-swimlane-vis-5.3.0.zip error...
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by haiyee** [comment]
In addition to change package.json, you will need to zip it under "/kibana/prelert_swimlane_vis-5.3.0/<rest of content>".

kibana/
└── prelert_swimlane_vis-5.3.0
    ├── LICENSE
    ├── NOTICE
    ├── README.md
    ├── index.js
    ├── package.json
    ├── public
    │   ├── lib
    │   │   └── bower_components
    │   │       └── flot
    │   │           ├── jquery.flot.js
    │   │           ├── jquery.flot.resize.js
    │   │           ├── jquery.flot.selection.js
    │   │           └── jquery.flot.time.js
    │   ├── prelert_logo_24.png
    │   ├── prelert_swimlane_vis.html
    │   ├── prelert_swimlane_vis.js
    │   ├── prelert_swimlane_vis.less
    │   ├── prelert_swimlane_vis_controller.js
    │   └── prelert_swimlane_vis_params.html
    └── resources
        ├── options.png
        ├── screenshot.png
        ├── step1.png
        ├── step2.png
        ├── step3.png
        └── visualization.png

**Comment by RedCloudDC** [comment]
done thank you (note: must be under the kibana/plugins dir)

**Comment by peteharverson** [comment]
I have created a v5.3.0 release today, and also published releases for Kibana 5.3.1 and 5.3.2. As @haiyee commented, package.json contains the version information, and the zip file needs to have the correct structure, with in your example, a `prelert_swimlane_vis-5.3.2` folder below the top-level `kibana` folder.
