### ISSUE TITLE
Adding legend to UI

### ISSUE THREAD

**Issue by hoangv2** [prelert/kibana-swimlane-vis#19]
Can we have the legend visible on the UI, next to the heatmap (eg, right, or bottom)?

**Comment by mpaduada** [comment]
Assuming that @hoangv2 is asking about a legend indicating how the colours correspond to the band threshold ranges, then yes, please add this feature.

+1

**Comment by peteharverson** [comment]
Thank you @hoangv2 and @mpaduada for the request. For the v5.3.0 release, I have added a legend above the swimlane, next to the aggregation interval control, which displays the configured lower threshold values for each of the colours. See example below:

![image](https://cloud.githubusercontent.com/assets/7405507/25617977/cc9e4ea6-2f3c-11e7-8055-94127c5739bc.png)

The legend can be hidden if desired via the Options tab when creating or editing the swimlane under Kibana Visualize.

Hope this meets your requirements.

**Comment by hoangv2** [comment]
Thanks much @peteharverson !

**Comment by peteharverson** [comment]
Closing issue. The legend was added for the v5.3.0 release.
