### ISSUE TITLE
5.4.1 version

### ISSUE THREAD

**Issue by aryzle** [prelert/kibana-swimlane-vis#23]
great plugin! Any news on a 5.4.1 version? would love to use this in our production system

**Comment by peteharverson** [comment]
Thanks for the feedback. Glad you like the plugin! Apologies for the delay in packaging up releases for the 5.4 releases of the elastic stack. I have just published v5.4.0 and v5.4.1 releases, and a v5.4.2 release should be available shortly. The 5.4 releases include the ability to customize the colors used for the different bands, as added by @pacurtin.

Do report any issues that you find, and we welcome any enhancement requests, or indeed contributions.
