### ISSUE TITLE
Kibana 5.5 update

### ISSUE THREAD

**Issue by deyb** [prelert/kibana-swimlane-vis#29]
Could you please update the plugin for Kibana 5.5.0 release ? I tried changing the pakcage.json to a newer version but it doesn't seem to work. The optimization failed and it didn't show up in the dashbaord.

Thanks

**Comment by peteharverson** [comment]
I have just published a v5.5.0 release, which includes the edits made in https://github.com/prelert/kibana-swimlane-vis/pull/28 by @fbaligand to support running on Kibana 5.5.0.

The install is working fine for me on 5.5.0. but please report any issues you find.

**Comment by deyb** [comment]
Thanks. I see your commit. It works fine now. Appreciate the quick changes made to support 5.5.0

**Comment by fbaligand** [comment]
@deyb 
Nice to see you appreciate :)
