### ISSUE TITLE
Not working with Kibana 5.5.2

### ISSUE THREAD

**Issue by Jal619** [prelert/kibana-swimlane-vis#31]
Hi  Team,

We have tried swimlane plugin for Kibana 5.5.2 .
BUt it's not working .

Please help.

Thanks & Regards,
Jalpesh

**Comment by peteharverson** [comment]
Sorry for the delay in packaging up a release for Kibana 5.5.2 @Jal619 . I have just published it to the [releases](https://github.com/prelert/kibana-swimlane-vis/releases) page.

In order for a version of Kibana to load a plugin, the version number in the plugin's `package.json` needs to match and the folder needs to have the correct structure, with here for example, a prelert_swimlane_vis-5.5.2 folder below the top-level kibana folder. For that reason, a new zip file needs to be released for each version of the elastic stack.

Thank you for your interest in the swimlanes plugin, and do report any issues you may find.
