### ISSUE TITLE
6.1.2 support

### ISSUE THREAD

**Issue by Stono** [prelert/kibana-swimlane-vis#38]
Hey, any chance of a release for 6.1.2?

Ta!
Karl

**Comment by Stono** [comment]
https://github.com/prelert/kibana-swimlane-vis/pull/39

**Comment by peteharverson** [comment]
Just packaged up a 6.1.2 release and published on the releases page. Many thanks for editing the README and package.json.

Thank you for your interest in the swimlanes plugin, and do report any issues you may find.
