### ISSUE TITLE
how can i install on kibana 5.6.9?

### ISSUE THREAD

**Issue by schosterbarak** [prelert/kibana-swimlane-vis#43]

**Comment by peteharverson** [comment]
Hi. Apologies for the delay in packaging up releases of the swimlane plugin for Kibana 5.6.x. I have just packaged up releases for 5.6.7, 5.6.8 and 5.6.9 and published them to the releases page.

The command for installing the 5.6.9 release is
```
bin/kibana-plugin install https://github.com/prelert/kibana-swimlane-vis/releases/download/v5.6.9/prelert_swimlane_vis-5.6.9.zip
```

I'll also aim to package up a release for Kibana `5.6.10`, which was released last week, in the next few days.

Thank you for your interest in the plugin, and do report any issues you may find.
