### ISSUE TITLE
Error installing 6.3.1

### ISSUE THREAD

**Issue by areyesram** [prelert/kibana-swimlane-vis#46]
Tried to install it using:

bin/kibana-plugin install https://github.com/prelert/kibana-swimlane-vis/releases/download/v6.3.1/prelert_swimlane_vis-6.3.1.zip

Gave me an error message:
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [prelert_swimlane_vis]. Expected [6.2.3]; found [6.3.0]"

**Comment by peteharverson** [comment]
Hi. Can you just confirm that you are installing the plugin into a 6.3.1 Kibana install? The error message you're seeing would seem to indicate that it's being installed into an older version of Kibana - the version of the plugin must match the Kibana version.

Did you uninstall the old version of the plugin first, with `bin/kibana-plugin remove prelert_swimlane_vis`?

I just tried installing into the plugin into a 6.3.1 Kibana install by:
- stopping Kibana
- uninstalling the old version with `bin/kibana-plugin remove prelert_swimlane_vis`
- installing the 6.3.1 plugin with `bin/kibana-plugin install https://github.com/prelert/kibana-swimlane-vis/releases/download/v6.3.1/prelert_swimlane_vis-6.3.1.zip`
- restarting Kibana

and didn't see any errors.
`

**Comment by areyesram** [comment]
Sorry, my bad. Wrong cluster.
