### ISSUE TITLE
Support version 6.3.2

### ISSUE THREAD

**Issue by nikolay** [prelert/kibana-swimlane-vis#47]
@peteharverson

**Comment by peteharverson** [comment]
Thanks for logging the issue. I have just packaged up a `6.3.2` release and published it to the releases page.

The command for installing the 6.3.2 release is:

```
bin/kibana-plugin install https://github.com/prelert/kibana-swimlane-vis/releases/download/v6.3.2/prelert_swimlane_vis-6.3.2.zip
```

Many thanks for your interest in the plugin, and do report any issues you may find.

**Comment by nikolay** [comment]
Thank you very much, @peteharverson!
