### ISSUE TITLE
Plugin prelert_swimlane_vis is incompatible with Kibana 6.6.0

### ISSUE THREAD

**Issue by neopolis** [prelert/kibana-swimlane-vis#51]
I updated Kibana to 6.6.0 version. There is no compatible prelert_swimlane_vis plugin for this version. 

When will you plan to prepare Plugin prelert_swimlane_vis [6.6.0] compatible with Kibana [6.6.0]?

Thanks.

**Comment by neopolis** [comment]
![image](https://user-images.githubusercontent.com/47552481/52772640-ac1b7980-3041-11e9-8013-47d4b2454aaf.png)

**Comment by peteharverson** [comment]
I hope to have a release for 6.6.0 in the next couple of days. I just need to make some minor edits to get it working on Kibana 6.6.

**Comment by peteharverson** [comment]
I just packaged up a 6.6.0 version of the swimlane and published it to the releases page. 

The command for installing the 6.6.0 version is
```
bin/kibana-plugin install https://github.com/prelert/kibana-swimlane-vis/releases/download/v6.6.0/prelert_swimlane_vis-6.6.0.zip
```

Please do report any issues you may find.
