### ISSUE TITLE
6.7.1 support

### ISSUE THREAD

**Issue by dettmern** [prelert/kibana-swimlane-vis#53]
Any plans 6.7.0/6.7.1 support? We're upgrading our cluster for maps features but still leverage this heavily for some of our dashboards.  Great plugin!

**Comment by peteharverson** [comment]
@dettmern sorry for the delay in replying. Yes, I do plan to release for 6.7. Hope to be able to get round to building the release in the next few days. Will update this issue once done. And thanks for the feedback!

**Comment by peteharverson** [comment]
I just packaged up releases for 6.7.0 and 6.7.1 and published to the releases page.

Install instructions can be found [here](https://github.com/prelert/kibana-swimlane-vis#installation)

Please do report any issues you may find.
