### ISSUE TITLE
KIbana 7.1.1 support

### ISSUE THREAD

**Issue by karthikgreentrend** [prelert/kibana-swimlane-vis#54]
I am waiting for 7.1.1 release if you need any helping hand please let me know

**Comment by peteharverson** [comment]
Thanks for raising the issue for 7.1 support @qakart . I need to check first if any code changes are required to support running on KIbana 7.x, and can then look at packaging up releases for 7.0 and 7.1. Will update this issue as soon as possible.

**Comment by Duella12345** [comment]
Hi Pete, I would also be interested in a 7.1.1 release

**Comment by peteharverson** [comment]
I just packaged up releases for 7.1.0 and 7.1.1 and published to the releases page.

Install instructions can be found [here](https://github.com/prelert/kibana-swimlane-vis#installation)

Please do report any issues you may find.
