### ISSUE TITLE
Kibana 7.2 support

### ISSUE THREAD

**Issue by tonykoval** [prelert/kibana-swimlane-vis#56]
Hi, I tried with the latest version (7.2.0) and I got error in console:
`TypeError: Cannot read property 'id' of undefined at prelert_swimlane_vis_controller.js:115`

**Comment by peteharverson** [comment]
Thanks for trying the swimlane out on Kibana 7.2.0 @tonykoval . I haven't packaged up a release or tested on 7.2.0 myself yet. It's possible there has been some change to the Kibana visualization API between 7.1 and 7.2 which will require a code change to the swimlane visualization. I'll aim to try it out on 7.2.0 in the next few days and will update this issue.

**Comment by tonykoval** [comment]
Thanks. :)

**Comment by peteharverson** [comment]
@tonykoval I've now tested the plugin on Kibana 7.2.0 and have hit the same error that you reported. There have been some fairly major changes to the plugin API in Kibana 7.2, as reported in this [blog](https://www.elastic.co/blog/kibana-plugin-api-changes-in-7-2), so I'll need to make a few code changes to the swimlane visualization to get it working on 7.2. Looking into those now, and will update this issue when I've found a resolution.

**Comment by tonykoval** [comment]
update to 7.3.0, https://www.elastic.co/blog/kibana-plugin-api-changes-in-7.3

**Comment by chopchop505** [comment]
Looking forward to upgrading to 7.3 as well.

**Comment by peteharverson** [comment]
I have now packaged up releases for 7.2.0 and 7.2.1 and published to the releases page.

Install instructions can be found [here](https://github.com/prelert/kibana-swimlane-vis#installation)

I hope to have releases for 7.3 shortly, but there were several [changes](https://www.elastic.co/blog/kibana-plugin-api-changes-in-7.3) to the Kibana plugin API for 7.3 so some code changes are likely to be required.

**Comment by peteharverson** [comment]
I have now packaged up releases for 7.3.0, 7.3.1 and 7.3.2 and published to the releases page.

Install instructions can be found [here](https://github.com/prelert/kibana-swimlane-vis#installation)

Please do report any issues you may find.
