### ISSUE TITLE
Kibana plugin for 7.4

### ISSUE THREAD

**Issue by krishnaprasadhg** [prelert/kibana-swimlane-vis#58]
Kindly publish kibana plugins for v 7.4. As of now plugins avaialble till 7.2 only.

**Comment by peteharverson** [comment]
Thank you for creating this issue @krishnaprasadhg. There have been a few changes to the Kibana visualization API between v7.2 and 7.3 and 7.4 so there will be a few code changes required. I will try and take a look in the next few days and will then update this issue.

**Comment by krishnaprasadhg** [comment]
Thanks for your response @peteharverson 
i have just unzipped -->edited 7.2.1 package.json & folder name --> zipped -->installed kibana plugin for 7.4.0.
So far its working fine!

**Comment by peteharverson** [comment]
@krishnaprasadhg I have now packaged up releases for 7.4.0, 7.4.1 and 7.4.2 and published to the releases page. As you [commented](https://github.com/prelert/kibana-swimlane-vis/issues/58#issuecomment-558119896), the only code changes required were to `package.json` and the folder name in the zip, but please do report any issues you may find.

Install instructions can be found [here](https://github.com/prelert/kibana-swimlane-vis#installation)
