### ISSUE TITLE
ability to add additional color (enhancement)

### ISSUE THREAD

**Issue by shgidi** [prelert/kibana-swimlane-vis#6]

**Comment by gerardseeto** [comment]
Can we also add ability to invert the values so red shows for low numerical values for example to signify things getting more urgent/risky

Band thresholds

Enter the lower threshold for each color band:

  
365
 
  
180
 
  
90
 
  
60
 
  
30
 
Tooltip formatting

**Comment by peteharverson** [comment]
@gerardseeto it is now possible to configure the colors used for each band using the colorpickers on the Options tab, which was added in #21. This was included for the v5.4 releases. It is not yet possible to add (or remove) additional bands.

**Comment by peteharverson** [comment]
The ability to add or remove threshold bands has been added in the 6.1.0 release, with 'add' and 'delete' buttons added to the band threshold controls in the Options tab:

![image](https://user-images.githubusercontent.com/7405507/35271332-a734a2c8-0029-11e8-9320-75f30ec249af.png)

Closing issue.
