### ISSUE TITLE
7.5.1 Build

### ISSUE THREAD

**Issue by chopchop505** [prelert/kibana-swimlane-vis#61]
Love the plugin! Will you all be releasing a build for 7.5.1 soon?

**Comment by peteharverson** [comment]
Thanks for the feedback @chopchop505 ! Yes, I will look at packaging up releases for 7.5 in the next few days. I am not sure yet if there were any significant changes in the Kibana visualization API between 7.4 and 7.5, so whether code changes are required to the plugin, or if it just needs the version updated in `package.json`. Will update this issue as soon as I know more.

**Comment by peteharverson** [comment]
Turns out there have been some significant changes to the Kibana visualization API between 7.4 and 7.5 and some code changes to the swimlane plugin are needed, so turnaround time to produce 7.5.x releases will take a few days.

**Comment by chopchop505** [comment]
Great @peteharverson thanks for the update!

**Comment by peteharverson** [comment]
I have packaged up releases for 7.5.0, 7.5.1 and 7.5.2 and published them to the releases page.

Install instructions can be found [here](https://github.com/prelert/kibana-swimlane-vis#installation).

Please do report any issues you may find.
