### ISSUE TITLE
For Kibana 7.6.x versions

### ISSUE THREAD

**Issue by chandra2037** [prelert/kibana-swimlane-vis#62]
Is there any plan to release for new Kibana 7.6.x versions?

Thanks

**Comment by peteharverson** [comment]
Yes @chandra2037 I will try and take a look at a 7.6.x build in the next few days. I haven't checked yet if any code changes are required due to changes in the Kibana visualization API between 7.5 and 7.6.

**Comment by peteharverson** [comment]
Sorry for the delay in publishing a 7.6.x build @chandra2037 . There were a few changes to the Kibana plugin API in 7.6, which has required some code changes to the swimlane plugin, but I'm almost done with the required edits now, so should have releases available for 7.6.x in the next day or so.

**Comment by chandra2037** [comment]
Thank you @peteharverson 

Very helpful. I am seeing 7.6.0. 

Now, 7.6.2 released, very fast releases :)

**Comment by peteharverson** [comment]
@chandra2037 I have now packaged up releases for 7.6.1 and 7.6.2 as well as 7.6.0, and published them to the releases page.

Please do report any issues you may find.
