### ISSUE TITLE
Error happened when install kibana(4.5.4) plugin

### ISSUE THREAD

**Issue by tianchao-haohan** [prelert/kibana-swimlane-vis#7]
Kibana version: 4.5.4-1
OS: SUSE Linux Enterprise Server 12
c4dev@sles12-dev-01:~/workspace/tools> sudo /opt/kibana/bin/kibana plugin -i prelert_swimlane_vis -u https://github.com/prelert/kibana-swimlane-vis/archive/v0.1.0.tar.gz
Installing prelert_swimlane_vis
Attempting to transfer from https://github.com/prelert/kibana-swimlane-vis/archive/v0.1.0.tar.gz
Transferring 49666 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "unknown export types navbarExtensions, injectDefaultVars in plugin reporting"

**Comment by rostiar** [comment]
+1

**Comment by peteharverson** [comment]
Thanks for your interest in the Swimlane visualization. We have just tried installing the plugin into the latest Kibana 4.5.4 release, but all worked fine. We didn't see the error relating to navbarExtensions and injectDefaultVars. 

Could you please let us know what version of Elasticsearch you have installed. In the meantime we'll keep trying to reproduce.

**Comment by ebuildy** [comment]
Hello @tianchao-haohan , maybe you could post a Dockerfile so everyone can reproduce what you see?

I am running:

docker run -ti --rm kibana:4.5.4 /opt/kibana/bin/kibana plugin -i prelert_swimlane_vis -u https://github.com/prelert/kibana-swimlane-vis/archive/v0.1.0.tar.gz

And see no errors:

![](http://b3.ms/0xZnXBN29opO)

**Comment by tianchao-haohan** [comment]
@ebuildy  Thanks your response. It works well now. Besides, is that possible to support kibana 5.0?

**Comment by sophiec20** [comment]
Closing this ticket as works on 4.5.4.

@tianchao-haohan Have opened [#9](https://github.com/prelert/kibana-swimlane-vis/issues/9) to request support for Kibana 5.0
